config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }



  root 'static_pages#home'

  resources :users
  
 

  resources :posts do
    resources :comments
  end




  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/home', to: 'static_pages#home'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post


  validates :body, :user_id, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_post
    before_action :set_comment, only: [:show, :edit,:update ,:destroy]
    before_action :authorize_user!, only: [:edit, :update, :destroy]


    def index
        @comments = Comment.all
    end


    def show
    
        @comment = Comment.find(params[:id])

    
    end


    def new
        @comment = @post.comments.build
        
    end

    def create
        
        @comment = @post.comments.build(comment_params)
        @comment.user = current_user


        if @comment.save
            flash[:notice] = "The comment was created successfully"
            redirect_to post_path(@post)
          else
            flash[:alert] = "There was an error creating the comment"
            render :new, status: :unprocessable_entity
          end
    end


    def edit
        
    end




    def update
      @post = Post.find(params[:post_id])
      @comment = Comment.find(params[:id])
      if @comment.update(comment_params)
          flash[:notice] = "The comment was updated successfully"
          redirect_to post_path(@post)
        else
          flash[:alert] = "There was an error updating the comment"
          render :edit, status: :unprocessable_entity
        end
      
      
  end

    
    def destroy
        if @comment.destroy
          flash[:notice] = "The comment was deleted successfully"
          redirect_to post_path(@post), status: :see_other
        else
          flash[:alert] = "Error deleting comment"
          redirect_to post_path(@post)
        end
      end




    
    private


    
    
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
        @post = Post.find(params[:post_id])
    end

    def authorize_user!
      @comment = Comment.find(params[:id]) 
      unless current_user == @comment.user
        redirect_to posts_path, alert: 'You are not authorized to perform this action.'
      end
    end


    def comment_params
        params.require(:comment).permit(:body, :user_id)
    end

end
    

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card mb-3">
  <div class="card-body">
    <p>
      <strong>Body:</strong>
      <%= comment.body %>
    </p>
    <p>
      <strong>User Id:</strong>
      <%= comment.user_id %>
    </p>
    
    <% if user_signed_in? && current_user == comment.user %>
      <div class="d-flex justify-content-end mt-3">
        <%= link_to "Edit comment", edit_post_comment_path(comment.post, comment), class: "btn btn-outline-info btn-sm me-2" %>
        <%= link_to "Destroy", post_comment_path(comment.post, comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm" %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @post, @post.comments.build ], url: @post.new_record? ? posts_path : post_comments_path(@post)) do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>

  

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<div class="d-flex justify-content-center mt-5">
    <h1>Edit Comment</h1>
</div>



  <%= form_with(model: [ @post, @comment ]) do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/index.html.erb
<h1 class="m-3" >Comments</h1>


<ul>
  <% @comments.each do |comment| %>
    <li>
      <%= link_to comment.body, comment_path(comment) %>
    </li>
  <% end %>
</ul>

app/views/comments/new.html.erb
<div class=" d-flex justify-content-center mt-5"> 
    <h1 class="m-4">New Comment</h1>
</div>


    <div class="d-flex justify-content-center"><%= render 'form', comment: @comment %></div>
   
    

app/views/comments/show.html.erb
<%= render @comment%>