config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }



  root 'static_pages#home'

  resources :users
  
 

  resources :posts do
    resources :comments
  end




  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/home', to: 'static_pages#home'
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :tags
    has_many :comments, dependent: :destroy
    accepts_nested_attributes_for :comments
  
    validates :title, :content, :user_id, presence: true
    validates :answers_count, :likes_count, numericality: { greater_than_or_equal_to: 0 }
  
    after_validation :ensure_created_at_has_a_value
  
    private
  
    def ensure_created_at_has_a_value
      self.created_at ||= Date.current
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.new
    
  end

  def index
    @posts= Post.all
  end

  def show
    @post = Post.includes(:user, :tags).find(params[:id])

  end

 


  def create
    @post = current_user.posts.build(post_params)

    if params[:post][:comments_attributes] && params[:post][:comments_attributes]["0"][:body].blank?
      @post.comments = []  
    end

    if @post.save
      flash[:notice] = "Post created successfully"
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end



  def destroy
     
    @post = Post.find(params[:id])
    if @post.destroy
        flash[:message] = "The post was deleted successfully"
        redirect_to root_path, status: :see_other
    else
        flash[:message] = "Error deleting comment"
        redirect_to root_path
        end
   end




   def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post updated successfully"
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
    
    
  end


  





  private 
  def post_params
    params.require(:post).permit(:title, :content, :published_at, :answers_count, :likes_count, comments_attributes: [:body, :user_id])
  end

  

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>




  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  

  <div>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
    <% @post.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div >
    <%= form.label :published_at %><br>
    <%= form.datetime_field :published_at %>
  </div>


  <div>
    <%= form.label :answers_count %><br>
    <%= form.text_field :answers_count %>
    <% @post.errors.full_messages_for(:answers_count).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  
 <div>
    <%= form.label :likes_count %><br>
    <%= form.text_field :likes_count %>
    <% @post.errors.full_messages_for(:likes_count).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


<h2>Add Comment (Optional)</h2>
  <div>
    <%= form.fields_for :comments, @post.comments.build do |comment_fields| %>
      <div>
        <%= comment_fields.label :body, "Comment" %><br>
        <%= comment_fields.text_area :body %>
      </div>

      <div>
        <%= comment_fields.hidden_field :user_id, value: current_user.id %>
      </div>
    <% end %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
    <% @post.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :published_at %><br>
    <%= form.datetime_field :published_at %>
  </div>

  <div>
    <%= form.label :answers_count %><br>
    <%= form.text_field :answers_count %>
    <% @post.errors.full_messages_for(:answers_count).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :likes_count %><br>
    <%= form.text_field :likes_count %>
    <% @post.errors.full_messages_for(:likes_count).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1 class="m-3" >Tweets</h1>






<div class="row justify-content-center">
    <div class="col-auto">
      <table class="table table-responsive table-bordered">
         <tr>
    <th>Id </th>
    <th>Title </th>
    <th>Comments</th>
      </tr>
<% @posts.order(:id).each do |post| %>
  <tr>
    <td><%= post.id%></td>
    <td><%= link_to post.title, post%></td>
    <td><%= post.comments.count%></td>
    
    
  </tr>
  <% end %>
      </table>
    <%= link_to "New Post", new_post_path, class:"btn btn-outline-primary" %>
    </div>
    
  </div>

app/views/posts/new.html.erb
<div class="container"> 

    <div class="row align-items-center">

        <div class="col-sm-4 my-auto">
            <h1 class="  off-set-3">New Post</h1>
        </div>
        

        <div class="col-sm-6 mt-4">
            <%= render "form", post: @post %>
        </div>

    </div>
    

</div>





  

app/views/posts/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">

      <div class="card">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
              <h2 class="blog-post-title"><%= @post.title %></h2>
              <h4 class="lead text-muted"><%= @post.user.name %></h4>
            </div>
            <div>
              <% if user_signed_in? && current_user == @post.user %>
                <button type="button" class="btn btn-outline-info btn-sm"><%= link_to "Edit Post", edit_post_path(@post) %></button>
                <%= link_to "Destroy", post_path(@post), class: "btn btn-outline-danger btn-sm", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              <% end %>
            </div>
          </div>

          <p class="blog-post-content"><%= @post.content %></p>

          <div class="mt-4">
            <h5>Tags:</h5>
            <p class="badge bg-secondary">
              <% @post.tags.each do |tag| %>
                <span class="badge bg-secondary"><%= tag.name %></span>
              <% end %>
            </p>
          </div>

          <hr>

          <h4 class="m-4">Comments</h4>
          <%= render @post.comments %>

          <% if user_signed_in? %>
            <button type="button" class="btn btn-outline-info mt-4"><%= link_to "Add Comment", new_post_comment_path(@post) %></button>
          <% else %>
            <%= link_to "Login to comment", new_user_session_path, class: "btn btn-outline-primary mt-4" %>
          <% end %>
          
          <button type="button" class="btn btn-outline-secondary mt-4"><%= link_to "Back to Posts", posts_path %></button>
        </div>
      </div>
      
    </div>
  </div>
</div>